name: pizzeria_menu
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  provider: ^5.0.0
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  cupertino_icons: ^1.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true


  assets:
    - assets/images/


